listen_address = "127.0.0.1"
listen_port = "3000"
url = "http://localhost:3000/"
# the below paths are relative to this
registry_path = "/app"

# error, warn, info, debug, trace
[log]
level = "debug"
path = "logs"
format = "human"
roll_period = "never"
# minimizes logs from other crates (sqlx, hyper, etc.)
extra_logging = false
#env_filter = 

[storage]
driver = "filesystem"
path = "blobs"

[database]
type = "sqlite"
path = "test.db"

[tls]
enable = false
key = "key.pem"
cert = "cert.pem"

#[ldap]
#connection_url = "ldap://localhost:389"
#bind_dn = "cn=admin,dc=planetexpress,dc=com"
#bind_password = "GoodNewsEveryone"
#user_base_dn = "ou=people,dc=planetexpress,dc=com"
#group_base_dn = "ou=people,dc=planetexpress,dc=com"
#
#user_search_filter = "(&(objectClass=person)(mail=%s))"
#group_search_filter = "(&(objectclass=groupOfNames)(member=%d))"
#
#admin_filter = "(memberOf=cn=admin_staff,ou=people,dc=planetexpress,dc=com)"
#login_attribute = "mail"
#display_name_attribute = "displayName"